### PR TITLE
Support a default provider for OIDC + new example

### PR DESCRIPTION
**Pull request by m-mohr**
- Support a default client for OIDC
- Added a new example, also showing the default_clients

### CODE REVIEW

**Comment by soxofaan** [comment]
issue title should say "default provider" instead of "default client"?

**Comment by m-mohr** [comment]
Yes, indeed.

**Comment by soxofaan** [comment]
not ideal that you can not enforce that at most one provider can be flagged as default.

Alternatives:
- add a top level field "default_provider"  (type: string) to point to id of the default provider
- instead of "default" boolean flag: add "priority" integer field: highest priority is default provider
- first provider in list should be considered default provider

**Comment by m-mohr** [comment]
Yes, that's always the issue. You can't really provide a good way of doing it consistently. If you do "default_provider", then you can't check whether the value actually exists. Similarly for the priority, where you can't check whether all fields may be 0 for example.
The first in the list semantic could work, but is somewhat giving a meaning to something a provider may not have chosen explicitly as he may have implemented it in 1.0 where this was not the case yet. Let's say it's not really breaking, but also not really the nicest way of being backward-compatible.

**Comment by m-mohr** [comment]
@soxofaan Would you prefer the alternative of the first array element being the default? I think that's the only option that would lead to a bit more consistency.

**Comment by soxofaan** [comment]
Yes, "first of list" would be my preference. It introduces no real API changes, except for documenting this "convention". It would also work for automatically for backends that just specify a single OIDC provider.

Second preference would be new "default_provider" field because if there is an inconsistency then it will fail in a clear way. If you have inconsistency with the boolean "default" flags, then some implementations might still accept that (because they pick the first match they find).

**Comment by m-mohr** [comment]
I'll update this PR to work with the array convention.

**Comment by m-mohr** [comment]
PR has been updated. This really feels much better integrated, it also works out of the box with the Web Editor implementation.

**Review by soxofaan — APPROVED** [review]

**Pull request merged**
