### PR TITLE
Multiple files returned by sync. processing #349

### PR DESCRIPTION
**Pull request by m-mohr**
Clarified that `POST /result` may return multiple files as a tar. #349

This is potentially already allowed, at least there's no direct exclusion of the multipart media types, but none of the clients seem to really handle it.

### CODE REVIEW

**Comment by m-mohr** [comment]
Please note that the tar recommendation is only for synchronous processing where we basically can only return a single binary blob. This doesn't affect batch jobs or secondary web services. Also, it's just a recommendation. Back-ends can still throw an error. 

If there are no objections to this PR in the next two weeks, I'd merge it as it helps with a number of cases that are not yet specified in the API for sync. processing. Otherwise, please propose an alternative in a PR.

**Comment by soxofaan** [comment]
any reason to pick tar instead of other archive format like zip, gzip or bzip?

(I'm not against tar, just checking whether tar is the best/easiest solution for backends and clients)

**Comment by m-mohr** [comment]
@soxofaan tar is relatively easy to implement as it basically just concatenates files without the client having to implement various sorts of compressions. We basically just want to combine files and that's what tar does. Compression can be done through HTTP compression in gzip or so. For example, the tar js implementation is about 300 lines of code, while the zip implementations have thousands of lines. Same experience earlier in my career with PHP. I guess for the CLI libraries R and Python it's not a big deal whether they run tar or zip, right?

**Comment by soxofaan** [comment]
Python has tar/zip/gzip/bzip support out of the box in the standard library, so no problem there. 
On MacOS and a typical Linux desktop distro, you have support for tar/gzip and zip out of the box too.

But I was indeed wondering about tar support on windows. The client libraries should cover that in most cases.

**Pull request merged**
